package org.michaelfl.mychess.tuning;

import org.junit.jupiter.api.Test;
import org.michaelfl.mychess.tuning.TexelTuner.Sample;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Unit tests for the Texel tuning core, validated on synthetic data whose true
 * parameters are known, so recovery can be checked without any chess data.
 *
 * @author Michael Fleischhauer
 */
class TexelTunerTest {

    private static final double TRUE_K = 0.008;
    private static final int PARAM_COUNT = 6;
    private static final int SAMPLE_COUNT = 3000;

    @Test
    void sigmoidHasTheExpectedShape() {
        assertEquals(0.5, TexelTuner.sigmoid(0.0), 1e-12, "sigmoid(0) must be 0.5");
        assertTrue(TexelTuner.sigmoid(20.0) > 0.999, "large positive input approaches 1");
        assertTrue(TexelTuner.sigmoid(-20.0) < 0.001, "large negative input approaches 0");
        assertTrue(TexelTuner.sigmoid(1.0) > TexelTuner.sigmoid(-1.0), "sigmoid is monotonically increasing");
    }

    @Test
    void evaluateIsBaseEvalPlusFeatureDotParams() {
        Sample sample = new Sample(30.0, new double[] {1.0, -2.0, 0.0}, 1.0);
        double[] params = {10.0, 5.0, 7.0};

        // 30 + (1*10) + (-2*5) + (0*7) = 30
        assertEquals(30.0, TexelTuner.evaluate(sample, params), 1e-12, "linear evaluation");
    }

    @Test
    void aPerfectPredictorHasZeroError() {
        var data = syntheticData(new double[] {12.0, -8.0, 25.0, 0.0, 17.0, -30.0});

        // Evaluated at the generating params and K, every prediction equals the
        // (noiseless) result, so the mean squared error is zero.
        double error = TexelTuner.meanSquaredError(data, new double[] {12.0, -8.0, 25.0, 0.0, 17.0, -30.0}, TRUE_K);

        assertEquals(0.0, error, 1e-9, "the generating parameters must reproduce the labels exactly");
    }

    @Test
    void calibrateKRecoversTheGeneratingConstant() {
        double[] trueParams = {12.0, -8.0, 25.0, 0.0, 17.0, -30.0};
        var data = syntheticData(trueParams);

        double k = TexelTuner.calibrateK(data, trueParams);

        assertEquals(TRUE_K, k, TRUE_K * 0.05, "calibrated K must be within 5% of the generating K");
    }

    @Test
    void tuneStronglyReducesTheErrorTowardTheTrueParameters() {
        double[] trueParams = {12.0, -8.0, 25.0, 0.0, 17.0, -30.0};
        var data = syntheticData(trueParams);

        double[] start = new double[PARAM_COUNT];
        double startError = TexelTuner.meanSquaredError(data, start, TexelTuner.calibrateK(data, start));

        double[] tuned = TexelTuner.tune(data, start, TexelTuner.Config.defaults(), null);
        double tunedError = TexelTuner.meanSquaredError(data, tuned, TexelTuner.calibrateK(data, tuned));

        assertTrue(tunedError < startError * 0.1,
                "tuning must cut the error to under 10%% of the untuned error (start=%.5f, tuned=%.5f)"
                        .formatted(startError, tunedError));

        // The recovered parameters should point the same way as the true ones.
        for (int j = 0; j < PARAM_COUNT; j++) {
            if (Math.abs(trueParams[j]) > 5.0) {
                assertTrue(Math.signum(tuned[j]) == Math.signum(trueParams[j]),
                        "tuned parameter %d should have the same sign as the true value".formatted(j));
            }
        }
    }

    /**
     * Builds a deterministic synthetic dataset whose labels are generated by the
     * given true parameters through the same sigmoid model the tuner fits, so a
     * correct tuner can recover them.
     */
    private static List<Sample> syntheticData(double[] trueParams) {
        var random = new Random(42L);
        var data = new ArrayList<Sample>(SAMPLE_COUNT);

        for (int i = 0; i < SAMPLE_COUNT; i++) {
            double baseEval = (random.nextDouble() - 0.5) * 300.0;
            double[] features = new double[PARAM_COUNT];

            for (int j = 0; j < PARAM_COUNT; j++) {
                features[j] = random.nextInt(3) - 1; // -1, 0 or +1
            }

            double eval = baseEval;
            for (int j = 0; j < PARAM_COUNT; j++) {
                eval += features[j] * trueParams[j];
            }

            double result = TexelTuner.sigmoid(TRUE_K * eval);
            data.add(new Sample(baseEval, features, result));
        }

        return data;
    }
}
