#!/usr/bin/env python3
"""Render the re-probed anchor findings as a readable, ranked report.

The anchor corpus had the opposite problem from the lichess one: it was *verified* but not
*readable*. 81 findings sat in a JSON array for twelve days and five of them became tests,
because picking a case out of raw JSON means running the tools again for every candidate.
The lichess corpus does not have that problem — `lichess-blunder-scan.py` writes
`test-results/lichess/blunders.md`, and its **Test** column makes the unconsumed cases
obvious at a glance. This gives the anchor corpus the same thing.

One row per finding, carrying everything needed to decide whether to work it up:

* whether the current build **still plays it**, and at which depths — the pin depth for a
  characterization test, which is not always `SCANNER_DEPTH`
* the **holding move** and the **refutation line** from Stockfish 18 at depth 22
* whether a test already covers it, detected the way `lichess-blunder-scan.py` does it: by
  grepping the test sources for the FEN

Inputs are the two JSONL files produced by `reprobe-anchor-findings.py` and
`refute-anchor-findings.py`; this script only formats, so it can be re-run freely.

Usage::

    ../lichess-bot/venv/bin/python tools/report-anchor-blunders.py

@author Michael Fleischhauer
"""

import json
import sys
from pathlib import Path

try:
    import chess
except ImportError as missing:
    sys.exit(f"missing dependency: {missing.name}. Run this with a Python that has "
             f"python-chess, e.g. ../lichess-bot/venv/bin/python")

REPO_ROOT = Path(__file__).resolve().parent.parent
REPROBE = REPO_ROOT / "test-results" / "anchor-reprobe-4.6.0.jsonl"
REFUTE = REPO_ROOT / "test-results" / "anchor-refutations.jsonl"
TEST_SOURCES = REPO_ROOT / "src" / "test" / "java" / "org" / "michaelfl" / "mychess"
OUTPUT = REPO_ROOT / "test-results" / "anchor-blunders-4.6.0.md"

#: Below this the position was already lost and the move says nothing about what lost it —
#: § 11.3's pick criterion, in centipawns.
NOT_YET_LOST_CP = -100

REFUTATION_PLIES = 4

#: Above this an evaluation is a mate score, not a material count. Rendering those as pawns
#: produces figures like "1012.67", which reads as a broken number rather than as the most
#: severe finding in the corpus.
MATE_THRESHOLD_PAWNS = 900


def pawns(value):
    """Evaluation as a printable string, with mate scores named rather than counted."""
    if value > MATE_THRESHOLD_PAWNS:
        return "mate"

    if value < -MATE_THRESHOLD_PAWNS:
        return "mated"

    return f"{value:+.2f}"


def read_jsonl(path):
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def covered_fens():
    """FENs already pinned by a test, matched on the placement field alone.

    The placement field rather than the whole FEN, because a test constant may legitimately
    carry different halfmove counters — the same trick `lichess-blunder-scan.py` uses.
    """
    corpus = "\n".join(p.read_text(encoding="utf-8", errors="ignore")
                       for p in TEST_SOURCES.rglob("*.java"))

    return corpus


def label(board, move_number, san):
    return f"{move_number}.{san}" if board.turn == chess.WHITE else f"{move_number}...{san}"


def main():
    reprobe = {r["fen"]: r for r in read_jsonl(REPROBE)}
    refute = {r["fen"]: r for r in read_jsonl(REFUTE)}
    corpus = covered_fens()

    rows = []

    for fen, r in reprobe.items():
        f = refute[fen]
        board = chess.Board(fen)
        sign = 1 if board.turn == chess.WHITE else -1
        before = f["eval_before_cp"] * sign / 100
        after = f["eval_after_cp"] * sign / 100
        pins = [d["depth"] for d in r["per_depth"] if d["reproduces"]]
        rows.append({
            "label": label(board, r["move_number"], r["blunder_san"]),
            "anchor": r["anchor"],
            "color": "white" if board.turn == chess.WHITE else "black",
            "loss": before - after,
            "before": before,
            "after": after,
            "reproduces": r["reproduces_any"],
            "pins": pins,
            "holds": f["holds_san"],
            "refutation": " ".join(f["refutation_line"][:REFUTATION_PLIES]),
            "plays_now": [d for d in r["per_depth"] if d["depth"] == 8][0]["san"],
            "covered": fen.split(" ")[0] in corpus,
            "fen": fen,
        })

    rows.sort(key=lambda x: -x["loss"])
    reproducing = [x for x in rows if x["reproduces"]]
    repaired = [x for x in rows if not x["reproduces"]]
    open_cases = [x for x in rows if not x["covered"]]

    out = []
    out.append("# myChess blunders found in the anchor bracket\n")
    out.append(f"Generated by `tools/report-anchor-blunders.py` from the re-probe of "
               f"{len(rows)} findings against the current build and the Stockfish 18 refutation "
               f"pass at depth 22. The underlying scan is `tools/scan-anchor-blunders.py`, "
               f"2026-08-17, on the v4.4.1 anchor PGNs (TSCP and Zeta Dva only).\n")
    out.append(f"**{len(rows)} findings**, all of which still measure at least 3.00 pawns of loss "
               f"under Stockfish 18 at depth 22. Restricted to positions that were not already "
               f"lost — a move played from below {NOT_YET_LOST_CP / 100:+.2f} says nothing about "
               f"the mistake that lost the game, so those 23 of the original 81 are excluded "
               f"rather than ranked.\n")
    out.append(f"**{len(reproducing)} still reproduce** on the current build and "
               f"**{len(repaired)} do not**. That split is the whole point of the report: a "
               f"reproducing case becomes a characterization test that passes today and fails "
               f"the day the defect is fixed; a repaired one becomes a guard. "
               f"**{len(open_cases)} are not covered by any test yet.**\n")
    out.append("Read **Pinned at** before writing a test. It is the set of depths at which the "
               "current build actually plays the move, and it is not always 8 — eight of the "
               "reproducing cases only reappear at depth 10 or 12, and pinning those at "
               "`SCANNER_DEPTH` produces a red test.\n")

    for title, subset, note in (
        ("Still reproducing — candidates for characterization tests", reproducing,
         "**Plays now** is the move at depth 8. Where it differs from the blunder, the case "
         "still reproduces deeper — see **Pinned at**."),
        ("Repaired since v4.4.1 — candidates for regression guards", repaired,
         "**Plays now** is what the current build chooses at depth 8 instead."),
    ):
        out.append(f"\n## {title}\n")
        out.append(note + "\n")
        out.append("| Loss | Before | After | Move | Anchor | Test | Pinned at | Holds | "
                   "Plays now | Refutation | FEN |")
        out.append("|---:|---:|---:|---|---|---|---|---|---|---|---|")

        for x in subset:
            pins = ", ".join(str(p) for p in x["pins"]) if x["pins"] else "—"
            loss = "mate given up" if abs(x["before"]) > MATE_THRESHOLD_PAWNS \
                or abs(x["after"]) > MATE_THRESHOLD_PAWNS else f"{x['loss']:.2f}"
            out.append(f"| **{loss}** | {pawns(x['before'])} | {pawns(x['after'])} | "
                       f"{x['label']} | {x['anchor']} | {'yes' if x['covered'] else 'no'} | "
                       f"{pins} | {x['holds']} | {x['plays_now']} | {x['refutation']} | "
                       f"`{x['fen']}` |")

    OUTPUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"{len(rows)} findings -> {OUTPUT}")
    print(f"  reproducing {len(reproducing)}, repaired {len(repaired)}, uncovered {len(open_cases)}")


if __name__ == "__main__":
    main()
